runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static/
- url: .*
  script: ae_hello_django.wsgi.application

libraries:
- name: lxml
  version: "latest"
- name: MySQLdb
  version: "latest"
- name: PIL
  version: "1.1.7"
- name: ssl
  version: latest