"""
Django settings for ae_hello_django project.

Generated by 'django-admin startproject' using Django 1.11.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'pn7)0kkfg&u1jee7&j^^2hyia+c#x$ohfug+h*&6v2qa6dt*wv'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'myapp.apps.MyappConfig',
    'home.apps.HomeConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ae_hello_django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ae_hello_django.wsgi.application'


def isLocal():
    try:
        return os.environ["SERVER_NAME"] in ["localhost","127.0.0.1"]
    except KeyError:
        return True


# 2st generation cloud sql
CLOUDSQL_PROJECT = 'justgo-188407'
CLOUDSQL_REGION = 'us-east1'
CLOUDSQL_INSTANCE = 'hellocloud-sql'

# 1st generation cloud sql
# CLOUDSQL_PROJECT = 'justgo-188407'
# CLOUDSQL_INSTANCE = 'hellosql-instance'


if isLocal():
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'hellocloud_database',
            'USER': 'admin',
            'PASSWORD': 'XXXX',
            'HOST': '173.194.228.248',
            'PORT': '3306',
        }
    }
else:
    DEBUG = False
    # 2st generation cloud sql
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'hellocloud_database',
            'USER': 'admin',
            'PASSWORD': 'XXXX',
            'HOST': '/cloudsql/' + CLOUDSQL_PROJECT + ":" + CLOUDSQL_REGION + ":" + CLOUDSQL_INSTANCE
        }
    }

    # 1st generation cloud sql
    # DATABASES = {
    #     'default': {
    #         'ENGINE': 'django.db.backends.mysql',
    #         'NAME': 'hellocloud_database',
    #         'USER': 'root',
    #         'HOST': '/cloudsql/' + CLOUDSQL_PROJECT + ":" + CLOUDSQL_INSTANCE,
    #     }
    # }



# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'static')

STATICFILES_DIRS = [
    # os.path.join(BASE_DIR, "static"),
]

TEMPLATE_DIRS = (os.path.join(BASE_DIR,  'templates'),)
